package com.woniu.pojo;
// Generated 2019-12-18 17:47:01 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Check generated by hbm2java
 */
public class Check implements java.io.Serializable {

	private Integer chId;
	private String chName;
	private Set chrecords = new HashSet(0);

	public Check() {
	}

	public Check(String chName, Set chrecords) {
		this.chName = chName;
		this.chrecords = chrecords;
	}

	public Integer getChId() {
		return this.chId;
	}

	public void setChId(Integer chId) {
		this.chId = chId;
	}

	public String getChName() {
		return this.chName;
	}

	public void setChName(String chName) {
		this.chName = chName;
	}

	public Set getChrecords() {
		return this.chrecords;
	}

	public void setChrecords(Set chrecords) {
		this.chrecords = chrecords;
	}

	@Override
	public String toString() {
		return "Check [chId=" + chId + ", chName=" + chName + "]";
	}

	
}
