package com.woniu.pojo;
// Generated 2019-12-18 17:47:01 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Chrecord generated by hbm2java
 */
public class Chrecord implements java.io.Serializable {

	private Integer chReId;
	private Check check;
	private Integer stuId;
	private Date chReTime;

	public Chrecord() {
	}

	public Chrecord(Check check, Integer stuId, Date chReTime) {
		this.check = check;
		this.stuId = stuId;
		this.chReTime = chReTime;
	}

	public Integer getChReId() {
		return this.chReId;
	}

	public void setChReId(Integer chReId) {
		this.chReId = chReId;
	}

	public Check getCheck() {
		return this.check;
	}

	public void setCheck(Check check) {
		this.check = check;
	}

	public Integer getStuId() {
		return this.stuId;
	}

	public void setStuId(Integer stuId) {
		this.stuId = stuId;
	}

	public Date getChReTime() {
		return this.chReTime;
	}

	public void setChReTime(Date chReTime) {
		this.chReTime = chReTime;
	}

}
