package com.woniu.pojo;
// Generated 2019-12-20 10:30:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Chrecord generated by hbm2java
 */
public class Chrecord implements java.io.Serializable {

	private Integer chReId;
	private Student student;
	private Date chReTime;
	private Integer chId;

	public Chrecord() {
	}

	public Chrecord(Student student, Date chReTime, Integer chId) {
		this.student = student;
		this.chReTime = chReTime;
		this.chId = chId;
	}

	public Integer getChReId() {
		return this.chReId;
	}

	public void setChReId(Integer chReId) {
		this.chReId = chReId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getChReTime() {
		return this.chReTime;
	}

	public void setChReTime(Date chReTime) {
		this.chReTime = chReTime;
	}

	public Integer getChId() {
		return this.chId;
	}

	public void setChId(Integer chId) {
		this.chId = chId;
	}

}
