package com.woniu.pojo;
// Generated 2019-12-18 17:47:01 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private Integer eId;
	private Stage stage;
	private Student student;
	private String escore;
	private Date edate;

	public Exam() {
	}

	public Exam(Integer eId, Stage stage, Student student, String escore, Date edate) {
		super();
		this.eId = eId;
		this.stage = stage;
		this.student = student;
		this.escore = escore;
		this.edate = edate;
	}

	public Integer geteId() {
		return eId;
	}

	public void seteId(Integer eId) {
		this.eId = eId;
	}

	public Stage getStage() {
		return stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getEscore() {
		return escore;
	}

	public void setEscore(String escore) {
		this.escore = escore;
	}

	public Date getEdate() {
		return edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

	@Override
	public String toString() {
		return "Exam [eId=" + eId + ", stage=" + stage + ", student=" + student + ", escore=" + escore + ", edate="
				+ edate + "]";
	}

	

	


	

	
}
