package com.woniu.pojo;
// Generated 2019-12-20 11:15:59 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private Integer eid;
	private Student student;
	private Integer staId;
	private Integer escore;
	private Date edate;

	public Exam() {
	}

	public Exam(Student student, Integer staId, Integer escore, Date edate) {
		this.student = student;
		this.staId = staId;
		this.escore = escore;
		this.edate = edate;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Integer getStaId() {
		return this.staId;
	}

	public void setStaId(Integer staId) {
		this.staId = staId;
	}

	public Integer getEscore() {
		return this.escore;
	}

	public void setEscore(Integer escore) {
		this.escore = escore;
	}

	public Date getEdate() {
		return this.edate;
	}

	public void setEdate(Date edate) {
		this.edate = edate;
	}

}
