package com.woniu.pojo;
// Generated 2019-12-18 17:47:01 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private Integer staId;
	private String staName;
	private String staWeek;
	private Set grades = new HashSet(0);
	private Set exams = new HashSet(0);

	public Stage() {
	}

	public Stage(String staName, String staWeek, Set grades, Set exams) {
		this.staName = staName;
		this.staWeek = staWeek;
		this.grades = grades;
		this.exams = exams;
	}

	public Integer getStaId() {
		return this.staId;
	}

	public void setStaId(Integer staId) {
		this.staId = staId;
	}

	public String getStaName() {
		return this.staName;
	}

	public void setStaName(String staName) {
		this.staName = staName;
	}

	public String getStaWeek() {
		return this.staWeek;
	}

	public void setStaWeek(String staWeek) {
		this.staWeek = staWeek;
	}

	public Set getGrades() {
		return this.grades;
	}

	public void setGrades(Set grades) {
		this.grades = grades;
	}

	public Set getExams() {
		return this.exams;
	}

	public void setExams(Set exams) {
		this.exams = exams;
	}

}
