package com.woniu.pojo;
// Generated 2019-12-18 17:47:01 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;
	private Set gradesForHid = new HashSet(0);
	private Set gradesForTid = new HashSet(0);
	private Set userRoles = new HashSet(0);

	public User() {
	}

	public User(String uname, String upwd, Set gradesForHid, Set gradesForTid, Set userRoles) {
		this.uname = uname;
		this.upwd = upwd;
		this.gradesForHid = gradesForHid;
		this.gradesForTid = gradesForTid;
		this.userRoles = userRoles;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public Set getGradesForHid() {
		return this.gradesForHid;
	}

	public void setGradesForHid(Set gradesForHid) {
		this.gradesForHid = gradesForHid;
	}

	public Set getGradesForTid() {
		return this.gradesForTid;
	}

	public void setGradesForTid(Set gradesForTid) {
		this.gradesForTid = gradesForTid;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", uname=" + uname + ", upwd=" + upwd + "]";
	}

	

}
